# Generated by Django 5.0.3 on 2024-04-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.TextField()),
                ('cname', models.TextField()),
                ('model', models.TextField()),
                ('img', models.ImageField(upload_to='media/gallery_picture')),
                ('price', models.TextField()),
                ('engine', models.TextField()),
                ('power', models.TextField()),
                ('torque', models.TextField()),
                ('clearence', models.TextField()),
                ('mileage', models.TextField()),
                ('tank', models.TextField()),
                ('gearbox', models.TextField()),
                ('height', models.TextField()),
                ('length', models.TextField()),
                ('width', models.TextField()),
                ('weight', models.TextField()),
                ('wheelbase', models.TextField()),
            ],
        ),
    ]
